### PR TITLE
Overhaul the style

### LINKED ISSUE #20: Add dark mode support
Currently the site lacks dark-mode support entirely, this is not so great as then Browser Extensions like "DarkReader" will take over in making the page have a dark-modish feeling. However those extensions usually don't work well with explicitly formatted content (like our markdown).

Thus the GitHub primer css sheet which we use should be extended to contain dark mode support. In the same thought we also could drop GitHub primer css all together and just use some trimmed-down version for the css support of our markdown.
Just the header and footer would need to be styled _manually_.

This dark mode support should be really simple and just work with the system preferences out of the box. As we're using a code highlighter that wants to know the color theme, we cannot just use some "prefers-color-scheme: dark" media query and should rely on the [VitePress Default Theme functionality](https://vitepress.dev/reference/site-config#appearance) instead (we might have to replicate some of it...).

### PR DESCRIPTION
**Pull request by Kuschel-Swein**
This PR overhauls the entire style-system to not ship github primer anymore. Thus reducing the bundle size.
Additionally we now added dark-mode support that automatically enables, based on the users preference. A nice side-effect of this overhaul is that we've now added support for the various [VitePress markdown extensions](https://vitepress.dev/guide/markdown), those together with GFM should ease the process of writing content (i.e. the "Note" or "Important" blocks from github are now available :tada:). Furthermore math-mode and footnotes are now supported.

> [!NOTE]
> Before approving, please re-check that the page looks fine with the new style.

---
Resolves #20

### CODE REVIEW

**Review by MariusLang — CHANGES_REQUESTED** [review]
The advent ad brings kind of inharmonic colours and shapes into the view. These changes would resolve the issues:

- Change the light mod `border` color of the whole ad to: #ccd4db (This is the dark color used for dividers)
- Change the dark mode `border` color of the whole ad to: #363c43 (This is the dark color used for dividers)
- Increase the `border-radius` to sth. from `0.35rem` to `0.4rem` so that it matches the `border-radius` of the button in the ad.

**Comment by Kuschel-Swein** [comment]
> * Change the light mod `border` color of the whole ad to: #ccd4db (This is the dark color used for dividers)

I guess you meant the `--borderColor-default` css variable? As there exists no color `#ccd4db` inside the entire styles.


> * Increase the `border-radius` to sth. from `0.35rem` to `0.4rem` so that it matches the `border-radius` of the button in the ad.

Both have the same border radius, `0.25rem`.

Otherwise I've implemented the changes.

**Comment by MariusLang** [comment]
Regarding the colors, yes. That's what I meant.

You are completely right. The value of the border radius is the same. However, the inner radius should be less than the outer radius for nested elements (see here: https://www.30secondsofcode.org/css/s/nested-border-radius/)

**Review by MariusLang — APPROVED** [review]
lgtm

**Pull request merged**
